<?php

namespace Database\Seeders;

use App\Models\Montadora;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MontadorasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $montadoras = array(
            array("id"=>"1", "nome"=>"CHEVROLET"),
            array("id"=>"2", "nome"=>"VOLKSWAGEN"),
            array("id"=>"3", "nome"=>"FIAT"),
            array("id"=>"4", "nome"=>"MERCEDES-BENZ"),
            array("id"=>"5", "nome"=>"CITROEN"),
            array("id"=>"6", "nome"=>"CHANA"),
            array("id"=>"7", "nome"=>"HONDA"),
            array("id"=>"8", "nome"=>"SUBARU"),
            array("id"=>"10", "nome"=>"FERRARI"),
            array("id"=>"11", "nome"=>"BUGATTI"),
            array("id"=>"12", "nome"=>"LAMBORGHINI"),
            array("id"=>"13", "nome"=>"FORD"),
            array("id"=>"14", "nome"=>"HYUNDAI"),
            array("id"=>"15", "nome"=>"JAC"),
            array("id"=>"16", "nome"=>"KIA"),
            array("id"=>"17", "nome"=>"GURGEL"),
            array("id"=>"18", "nome"=>"DODGE"),
            array("id"=>"19", "nome"=>"CHRYSLER"),
            array("id"=>"20", "nome"=>"BENTLEY"),
            array("id"=>"21", "nome"=>"SSANGYONG"),
            array("id"=>"22", "nome"=>"PEUGEOT"),
            array("id"=>"23", "nome"=>"TOYOTA"),
            array("id"=>"24", "nome"=>"RENAULT"),
            array("id"=>"25", "nome"=>"ACURA"),
            array("id"=>"26", "nome"=>"ADAMO"),
            array("id"=>"27", "nome"=>"AGRALE"),
            array("id"=>"28", "nome"=>"ALFA ROMEO"),
            array("id"=>"29", "nome"=>"AMERICAR"),
            array("id"=>"31", "nome"=>"ASTON MARTIN"),
            array("id"=>"32", "nome"=>"AUDI"),
            array("id"=>"34", "nome"=>"BEACH"),
            array("id"=>"35", "nome"=>"BIANCO"),
            array("id"=>"36", "nome"=>"BMW"),
            array("id"=>"37", "nome"=>"BORGWARD"),
            array("id"=>"38", "nome"=>"BRILLIANCE"),
            array("id"=>"41", "nome"=>"BUICK"),
            array("id"=>"42", "nome"=>"CBT"),
            array("id"=>"43", "nome"=>"NISSAN"),
            array("id"=>"44", "nome"=>"CHAMONIX"),
            array("id"=>"46", "nome"=>"CHEDA"),
            array("id"=>"47", "nome"=>"CHERY"),
            array("id"=>"48", "nome"=>"CORD"),
            array("id"=>"49", "nome"=>"COYOTE"),
            array("id"=>"50", "nome"=>"CROSS LANDER"),
            array("id"=>"51", "nome"=>"DAEWOO"),
            array("id"=>"52", "nome"=>"DAIHATSU"),
            array("id"=>"53", "nome"=>"VOLVO"),
            array("id"=>"54", "nome"=>"DE SOTO"),
            array("id"=>"55", "nome"=>"DETOMAZO"),
            array("id"=>"56", "nome"=>"DELOREAN"),
            array("id"=>"57", "nome"=>"DKW-VEMAG"),
            array("id"=>"59", "nome"=>"SUZUKI"),
            array("id"=>"60", "nome"=>"EAGLE"),
            array("id"=>"61", "nome"=>"EFFA"),
            array("id"=>"63", "nome"=>"ENGESA"),
            array("id"=>"64", "nome"=>"ENVEMO"),
            array("id"=>"65", "nome"=>"FARUS"),
            array("id"=>"66", "nome"=>"FERCAR"),
            array("id"=>"68", "nome"=>"FNM"),
            array("id"=>"69", "nome"=>"PONTIAC"),
            array("id"=>"70", "nome"=>"PORSCHE"),
            array("id"=>"72", "nome"=>"GEO"),
            array("id"=>"74", "nome"=>"GRANCAR"),
            array("id"=>"75", "nome"=>"GREAT WALL"),
            array("id"=>"76", "nome"=>"HAFEI"),
            array("id"=>"78", "nome"=>"HOFSTETTER"),
            array("id"=>"79", "nome"=>"HUDSON"),
            array("id"=>"80", "nome"=>"HUMMER"),
            array("id"=>"82", "nome"=>"INFINITI"),
            array("id"=>"83", "nome"=>"INTERNATIONAL"),
            array("id"=>"86", "nome"=>"JAGUAR"),
            array("id"=>"87", "nome"=>"JEEP"),
            array("id"=>"88", "nome"=>"JINBEI"),
            array("id"=>"89", "nome"=>"JPX"),
            array("id"=>"90", "nome"=>"KAISER"),
            array("id"=>"91", "nome"=>"KOENIGSEGG"),
            array("id"=>"92", "nome"=>"LAUTOMOBILE"),
            array("id"=>"93", "nome"=>"LAUTOCRAFT"),
            array("id"=>"94", "nome"=>"LADA"),
            array("id"=>"95", "nome"=>"LANCIA"),
            array("id"=>"96", "nome"=>"LAND ROVER"),
            array("id"=>"97", "nome"=>"LEXUS"),
            array("id"=>"98", "nome"=>"LIFAN"),
            array("id"=>"99", "nome"=>"LINCOLN"),
            array("id"=>"100", "nome"=>"LOBINI"),
            array("id"=>"101", "nome"=>"LOTUS"),
            array("id"=>"102", "nome"=>"MAHINDRA"),
            array("id"=>"104", "nome"=>"MASERATI"),
            array("id"=>"106", "nome"=>"MATRA"),
            array("id"=>"107", "nome"=>"MAYBACH"),
            array("id"=>"108", "nome"=>"MAZDA"),
            array("id"=>"109", "nome"=>"MENON"),
            array("id"=>"110", "nome"=>"MERCURY"),
            array("id"=>"111", "nome"=>"MITSUBISHI"),
            array("id"=>"112", "nome"=>"MG"),
            array("id"=>"113", "nome"=>"MINI"),
            array("id"=>"114", "nome"=>"MIURA"),
            array("id"=>"115", "nome"=>"MORRIS"),
            array("id"=>"116", "nome"=>"MP LAFER"),
            array("id"=>"117", "nome"=>"MPLM"),
            array("id"=>"118", "nome"=>"NEWTRACK"),
            array("id"=>"119", "nome"=>"NISSIN"),
            array("id"=>"120", "nome"=>"OLDSMOBILE"),
            array("id"=>"121", "nome"=>"PAG"),
            array("id"=>"122", "nome"=>"PAGANI"),
            array("id"=>"123", "nome"=>"PLYMOUTH"),
            array("id"=>"124", "nome"=>"PUMA"),
            array("id"=>"125", "nome"=>"RENO"),
            array("id"=>"126", "nome"=>"REVA-I"),
            array("id"=>"127", "nome"=>"ROLLS-ROYCE"),
            array("id"=>"129", "nome"=>"ROMI"),
            array("id"=>"130", "nome"=>"SEAT"),
            array("id"=>"131", "nome"=>"UTILITARIOS AGRICOLAS"),
            array("id"=>"132", "nome"=>"SHINERAY"),
            array("id"=>"137", "nome"=>"SAAB"),
            array("id"=>"139", "nome"=>"SHORT"),
            array("id"=>"141", "nome"=>"SIMCA"),
            array("id"=>"142", "nome"=>"SMART"),
            array("id"=>"143", "nome"=>"SPYKER"),
            array("id"=>"144", "nome"=>"STANDARD"),
            array("id"=>"145", "nome"=>"STUDEBAKER"),
            array("id"=>"146", "nome"=>"TAC"),
            array("id"=>"147", "nome"=>"TANGER"),
            array("id"=>"148", "nome"=>"TRIUMPH"),
            array("id"=>"149", "nome"=>"TROLLER"),
            array("id"=>"150", "nome"=>"UNIMOG"),
            array("id"=>"154", "nome"=>"WIESMANN"),
            array("id"=>"155", "nome"=>"CADILLAC"),
            array("id"=>"156", "nome"=>"AM GEN"),
            array("id"=>"157", "nome"=>"BUGGY"),
            array("id"=>"158", "nome"=>"WILLYS OVERLAND"),
            array("id"=>"161", "nome"=>"KASEA"),
            array("id"=>"162", "nome"=>"SATURN"),
            array("id"=>"163", "nome"=>"SWELL MINI"),
            array("id"=>"175", "nome"=>"SKODA"),
            array("id"=>"239", "nome"=>"KARMANN GHIA"),
            array("id"=>"254", "nome"=>"KART"),
            array("id"=>"258", "nome"=>"HANOMAG"),
            array("id"=>"261", "nome"=>"OUTROS"),
            array("id"=>"265", "nome"=>"HILLMAN"),
            array("id"=>"288", "nome"=>"HRG"),
            array("id"=>"295", "nome"=>"GAIOLA"),
            array("id"=>"338", "nome"=>"TATA"),
            array("id"=>"341", "nome"=>"DITALLY"),
            array("id"=>"345", "nome"=>"RELY"),
            array("id"=>"346", "nome"=>"MCLAREN"),
            array("id"=>"534", "nome"=>"GEELY"),
            array("id"=>"7", "nome"=>"HONDA"),
            array("id"=>"27", "nome"=>"AGRALE"),
            array("id"=>"36", "nome"=>"BMW"),
            array("id"=>"59", "nome"=>"SUZUKI"),
            array("id"=>"98", "nome"=>"LIFAN"),
            array("id"=>"102", "nome"=>"MAHINDRA"),
            array("id"=>"132", "nome"=>"SHINERAY"),
            array("id"=>"133", "nome"=>"KASINSKI"),
            array("id"=>"135", "nome"=>"YAMAHA"),
            array("id"=>"136", "nome"=>"GARINNI"),
            array("id"=>"140", "nome"=>"SUNDOWN"),
            array("id"=>"170", "nome"=>"KAWASAKI"),
            array("id"=>"171", "nome"=>"POLARIS"),
            array("id"=>"176", "nome"=>"ADLY"),
            array("id"=>"177", "nome"=>"AMAZONAS"),
            array("id"=>"178", "nome"=>"APRILIA"),
            array("id"=>"179", "nome"=>"ATALA"),
            array("id"=>"180", "nome"=>"BAJAJ"),
            array("id"=>"181", "nome"=>"BENELLI"),
            array("id"=>"182", "nome"=>"BETA"),
            array("id"=>"183", "nome"=>"BIMOTA"),
            array("id"=>"184", "nome"=>"BRANDY"),
            array("id"=>"185", "nome"=>"BRAVA"),
            array("id"=>"186", "nome"=>"BRP"),
            array("id"=>"187", "nome"=>"BUELL"),
            array("id"=>"188", "nome"=>"BUENO"),
            array("id"=>"190", "nome"=>"CAGIVA"),
            array("id"=>"191", "nome"=>"MOBILETE"),
            array("id"=>"192", "nome"=>"DAELIM"),
            array("id"=>"193", "nome"=>"DAFRA"),
            array("id"=>"194", "nome"=>"DAYANG"),
            array("id"=>"195", "nome"=>"DAYUN"),
            array("id"=>"196", "nome"=>"DERBI"),
            array("id"=>"197", "nome"=>"DUCATI"),
            array("id"=>"198", "nome"=>"EMME"),
            array("id"=>"200", "nome"=>"FYM"),
            array("id"=>"201", "nome"=>"GAS GAS"),
            array("id"=>"202", "nome"=>"GREEN"),
            array("id"=>"203", "nome"=>"HAOBAO"),
            array("id"=>"204", "nome"=>"HARLEY-DAVIDSON"),
            array("id"=>"205", "nome"=>"HARTFORD"),
            array("id"=>"206", "nome"=>"HERO"),
            array("id"=>"207", "nome"=>"HUSABERG"),
            array("id"=>"208", "nome"=>"HUSQVARNA"),
            array("id"=>"209", "nome"=>"IROS"),
            array("id"=>"210", "nome"=>"JIAPENG VOLCANO"),
            array("id"=>"211", "nome"=>"JOHNNYPAG"),
            array("id"=>"212", "nome"=>"JONNY"),
            array("id"=>"213", "nome"=>"KAHENA"),
            array("id"=>"214", "nome"=>"KIMCO"),
            array("id"=>"215", "nome"=>"LAQUILA"),
            array("id"=>"216", "nome"=>"LANDUM"),
            array("id"=>"217", "nome"=>"LAVRALE"),
            array("id"=>"218", "nome"=>"LERIVO"),
            array("id"=>"219", "nome"=>"LON-V"),
            array("id"=>"220", "nome"=>"TRICICLO"),
            array("id"=>"221", "nome"=>"MALAGUTI"),
            array("id"=>"222", "nome"=>"MIZA"),
            array("id"=>"223", "nome"=>"MOTO GUZZI"),
            array("id"=>"224", "nome"=>"MRX"),
            array("id"=>"225", "nome"=>"MV AUGUSTA"),
            array("id"=>"226", "nome"=>"MVK"),
            array("id"=>"227", "nome"=>"ORCA"),
            array("id"=>"228", "nome"=>"PEGASSI"),
            array("id"=>"229", "nome"=>"PIAGGIO"),
            array("id"=>"230", "nome"=>"REGAL RAPTOR"),
            array("id"=>"231", "nome"=>"SANYANG"),
            array("id"=>"232", "nome"=>"SIAMOTO"),
            array("id"=>"233", "nome"=>"TARGOS"),
            array("id"=>"234", "nome"=>"TRAXX"),
            array("id"=>"235", "nome"=>"VENTO"),
            array("id"=>"236", "nome"=>"WUYANG"),
            array("id"=>"245", "nome"=>"GARRA"),
            array("id"=>"246", "nome"=>"X MOTOS"),
            array("id"=>"248", "nome"=>"TRICKER"),
            array("id"=>"253", "nome"=>"LAMBRETA"),
            array("id"=>"261", "nome"=>"OUTROS"),
            array("id"=>"269", "nome"=>"SCOOTER"),
            array("id"=>"281", "nome"=>"ZONGSHEN"),
            array("id"=>"282", "nome"=>"BIRELLI"),
            array("id"=>"294", "nome"=>"WALK MACHINE"),
            array("id"=>"297", "nome"=>"FBM"),
            array("id"=>"299", "nome"=>"ARIEL"),
            array("id"=>"340", "nome"=>"DUCAR"),
            array("id"=>"341", "nome"=>"DITALLY"),
            array("id"=>"342", "nome"=>"MARVA"),
            array("id"=>"343", "nome"=>"WOLVER"),
            array("id"=>"344", "nome"=>"KTM"),
            array("id"=>"347", "nome"=>"LEOPARD"),
            array("id"=>"348", "nome"=>"JAWA"),
            array("id"=>"349", "nome"=>"BULL"),
            array("id"=>"358", "nome"=>"CAN-AM"),
            array("id"=>"359", "nome"=>"ACELLERA"),
            array("id"=>"483", "nome"=>"VICTORY"),
            array("id"=>"484", "nome"=>"INDIAN"),
            array("id"=>"532", "nome"=>"BRAVAX"),
            array("id"=>"533", "nome"=>"GARELLI"),
            array("id"=>"1", "nome"=>"CHEVROLET"),
            array("id"=>"2", "nome"=>"VOLKSWAGEN"),
            array("id"=>"3", "nome"=>"FIAT"),
            array("id"=>"4", "nome"=>"MERCEDES-BENZ"),
            array("id"=>"6", "nome"=>"CHANA"),
            array("id"=>"13", "nome"=>"FORD"),
            array("id"=>"14", "nome"=>"HYUNDAI"),
            array("id"=>"16", "nome"=>"KIA"),
            array("id"=>"23", "nome"=>"TOYOTA"),
            array("id"=>"24", "nome"=>"RENAULT"),
            array("id"=>"27", "nome"=>"AGRALE"),
            array("id"=>"53", "nome"=>"VOLVO"),
            array("id"=>"84", "nome"=>"ISUZU"),
            array("id"=>"85", "nome"=>"IVECO"),
            array("id"=>"131", "nome"=>"UTILITARIOS AGRICOLAS"),
            array("id"=>"164", "nome"=>"TRAILER"),
            array("id"=>"167", "nome"=>"RANDON"),
            array("id"=>"242", "nome"=>"SCANIA"),
            array("id"=>"261", "nome"=>"OUTROS"),
            array("id"=>"263", "nome"=>"ONIBUS"),
            array("id"=>"266", "nome"=>"UTILITARIOS PESADOS"),
            array("id"=>"270", "nome"=>"MOTOR-HOME"),
            array("id"=>"274", "nome"=>"MAN"),
            array("id"=>"275", "nome"=>"NAVISTAR"),
            array("id"=>"277", "nome"=>"SINOTRUK"),
            array("id"=>"284", "nome"=>"SCHIFFER"),
            array("id"=>"285", "nome"=>"GUERRA"),
            array("id"=>"292", "nome"=>"MICHIGAN")
        );

        foreach ($montadoras as $montadora) {
            if (!Montadora::where('nome',$montadora['nome'])->exists()){
                DB::table('montadoras')->insert(
                    ['id'=>$montadora['id'],'nome'=>$montadora['nome']]
                );
            }
        }
    }
}
